### PR TITLE
Add error message if user_nl_blom includes hash comments

### PR DESCRIPTION
**Pull request by TomasTorsvik**
Same as #448, applied for the `release-1.6` branch.

### CODE REVIEW

**Review by jmaerz — APPROVED** [review]
Fine with me - thanks for taking care!

**Comment by jmaerz** [comment]
Any ideas, why the continuous integration testing fails? - I had similar issues in #449

**Comment by jmaerz** [comment]
As written in #451 one could handle the line also as user comment line - again, not knowing ad hoc, whether this introduces other side effects...

**Comment by TomasTorsvik** [comment]
> Any ideas, why the continuous integration testing fails? - I had similar issues in #449

@jmaerz - no, not really. Looks like something connected with linking to the MPI library. I see a lot of messages "undefined reference to `mpi_<somethig>' from building mod_xc.F.

**Comment by jmaerz** [comment]
@TomasTorsvik , yes, I saw it, similar in #449 - but there just with the undefined references to mpi functions...

**Review by JorgSchwinger — APPROVED** [review]
